name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --verbose

    - name: Archive Build Artifacts
      run: |
        mkdir -p release
        cp target/release/build release/
        tar -czvf release.tar.gz -C release .

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: release.tar.gz

    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        files: release.tar.gz        
        tag_name: v${{ github.sha }}
        release_name: "Release ${{ github.sha }}"
        body: "Automated release from GitHub Actions"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
